// Code generated by immutable tool. DO NOT EDIT.

package data

import (
	"github.com/gostdlib/base/values/generators/immutable/internal/generate/testdata/data/immutable"
)

// ImPassthrough is an immutable version of Passthrough.
// Passthrough's only field is a foreign type that happens to be called immutable.Map. It is not this generator's
// Map, so the field is passed through untouched, no immutable import of our own is emitted, and there is nothing
// for the foreign import to collide with.
type ImPassthrough struct {
	m immutable.Map[string, int]
}

// GetM retrieves the content of the field M.
func (r *ImPassthrough) GetM() immutable.Map[string, int] {
	return r.m
}

// SetM returns a copy of the struct with the field M set to the new value.
func (r *ImPassthrough) SetM(value immutable.Map[string, int]) ImPassthrough {
	n := copyImPassthrough(*r)
	n.m = value
	return n
}

// Mutable converts the immutable struct back to the original mutable struct.
func (r *ImPassthrough) Mutable() Passthrough {
	return Passthrough{
		M: r.m,
	}
}

// Immutable converts the mutable struct to the generated immutable struct.
func (r *Passthrough) Immutable() ImPassthrough {
	return ImPassthrough{
		m: r.M,
	}
}

func copyImPassthrough(s ImPassthrough) ImPassthrough {
	return s
}
