// Code generated by immutable tool. DO NOT EDIT.

package data

import ()

// ImUnnamed is an immutable version of Unnamed.
// Unnamed exercises a method with an unnamed receiver, which the generator must skip without panicking.
type ImUnnamed struct {
	id   uint64
	name string
}

// GetID retrieves the content of the field ID.
func (r *ImUnnamed) GetID() uint64 {
	return r.id
}

// SetID returns a copy of the struct with the field ID set to the new value.
func (r *ImUnnamed) SetID(value uint64) ImUnnamed {
	n := copyImUnnamed(*r)
	n.id = value
	return n
}

// GetName retrieves the content of the field Name.
func (r *ImUnnamed) GetName() string {
	return r.name
}

// SetName returns a copy of the struct with the field Name set to the new value.
func (r *ImUnnamed) SetName(value string) ImUnnamed {
	n := copyImUnnamed(*r)
	n.name = value
	return n
}

// Mutable converts the immutable struct back to the original mutable struct.
func (r *ImUnnamed) Mutable() Unnamed {
	return Unnamed{
		ID:   r.id,
		Name: r.name,
	}
}

// Immutable converts the mutable struct to the generated immutable struct.
func (r *Unnamed) Immutable() ImUnnamed {
	return ImUnnamed{
		id:   (r.ID),
		name: (r.Name),
	}
}

func copyImUnnamed(s ImUnnamed) ImUnnamed {
	return s
}
