// Code generated by immutable tool. DO NOT EDIT.

package data

import (
	"strconv"
)

// ImPair[T any, X any] is an immutable version of Pair[T any, X any].
// Pair has multiple type parameters and a value-receiver method exercising the *ast.IndexListExpr receiver form.
type ImPair[T any, X any] struct {
	a T
	b X
}

// GetA retrieves the content of the field A.
func (r *ImPair[T, X]) GetA() T {
	return r.a
}

// SetA returns a copy of the struct with the field A set to the new value.
func (r *ImPair[T, X]) SetA(value T) ImPair[T, X] {
	n := copyImPair[T, X](*r)
	n.a = value
	return n
}

// GetB retrieves the content of the field B.
func (r *ImPair[T, X]) GetB() X {
	return r.b
}

// SetB returns a copy of the struct with the field B set to the new value.
func (r *ImPair[T, X]) SetB(value X) ImPair[T, X] {
	n := copyImPair[T, X](*r)
	n.b = value
	return n
}

// Mutable converts the immutable struct back to the original mutable struct.
func (r *ImPair[T, X]) Mutable() Pair[T, X] {
	return Pair[T, X]{
		A: r.a,
		B: r.b,
	}
}

// Immutable converts the mutable struct to the generated immutable struct.
func (r *Pair[T, X]) Immutable() ImPair[T, X] {
	return ImPair[T, X]{
		a: (r.A),
		b: (r.B),
	}
}

func copyImPair[T any, X any](s ImPair[T, X]) ImPair[T, X] {
	return s
}

// Dump is a copy of the original method from Pair.
func (r ImPair[T, X]) Dump() string {
	return strconv.Itoa(42)
}
