// Code generated by immutable tool. DO NOT EDIT.

package data

import (
	"github.com/gostdlib/base/values/immutable"
)

// ImCopied is an immutable version of Copied.
// Copied is generated with -copy, so Immutable() copies its map and slice and the mutable struct stays
// usable afterwards.
type ImCopied struct {
	tags  immutable.Map[string, string] // Tags is copied on conversion rather than shared.
	names immutable.Slice[string]       // Names is copied on conversion rather than shared.
}

// GetTags retrieves the content of the field Tags.
// Tags is copied on conversion rather than shared.
func (r *ImCopied) GetTags() immutable.Map[string, string] {
	return r.tags
}

// SetTags returns a copy of the struct with the field Tags set to the new value.
// Tags is copied on conversion rather than shared.
func (r *ImCopied) SetTags(value immutable.Map[string, string]) ImCopied {
	n := copyImCopied(*r)
	n.tags = value
	return n
}

// GetNames retrieves the content of the field Names.
// Names is copied on conversion rather than shared.
func (r *ImCopied) GetNames() immutable.Slice[string] {
	return r.names
}

// SetNames returns a copy of the struct with the field Names set to the new value.
// Names is copied on conversion rather than shared.
func (r *ImCopied) SetNames(value immutable.Slice[string]) ImCopied {
	n := copyImCopied(*r)
	n.names = value
	return n
}

// Mutable converts the immutable struct back to the original mutable struct.
// The maps and slices this type wrapped are copied one level deep, so the returned value can be modified without
// changing the immutable one. A field declared immutable in Copied is returned as it is.
func (r *ImCopied) Mutable() Copied {
	return Copied{
		Tags:  r.tags.Copy(),
		Names: r.names.Copy(),
	}
}

// Immutable converts the mutable struct to the generated immutable struct.
// Every wrapped map and slice is copied one level deep, so writing to Copied's own maps and slices after
// this call no longer reaches the value returned here. What those maps and slices hold is still shared: a pointer,
// an interface, or a nested map or slice element is copied only if its type implements immutable.Copier.
func (r *Copied) Immutable() ImCopied {
	return ImCopied{
		tags:  immutable.NewMap[string, string](immutable.CopyMap(r.Tags)),
		names: immutable.NewSlice[string](immutable.CopySlice(r.Names)),
	}
}

func copyImCopied(s ImCopied) ImCopied {
	return s
}
