// Code generated by immutable tool. DO NOT EDIT.

package data

import (
	"github.com/gostdlib/base/values/immutable"
)

// ImSidecar is an immutable version of Sidecar.
// Sidecar is the target. Its raw map is wrapped, so the generated file imports the real immutable package —
// legally, because the foreign one stays behind with Unrelated.
type ImSidecar struct {
	raw immutable.Map[string, int]
}

// GetRaw retrieves the content of the field Raw.
func (r *ImSidecar) GetRaw() immutable.Map[string, int] {
	return r.raw
}

// SetRaw returns a copy of the struct with the field Raw set to the new value.
func (r *ImSidecar) SetRaw(value immutable.Map[string, int]) ImSidecar {
	n := copyImSidecar(*r)
	n.raw = value
	return n
}

// Mutable converts the immutable struct back to the original mutable struct.
// The maps and slices this type wrapped are copied one level deep, so the returned value can be modified without
// changing the immutable one. A field declared immutable in Sidecar is returned as it is.
func (r *ImSidecar) Mutable() Sidecar {
	return Sidecar{
		Raw: r.raw.Copy(),
	}
}

// Immutable converts the mutable struct to the generated immutable struct.
// Every map and slice is shared with the returned value rather than copied, so Sidecar must not be used
// again after this call: writing to it would change the value returned here. Generate with -copy if both need to
// stay usable.
func (r *Sidecar) Immutable() ImSidecar {
	return ImSidecar{
		raw: immutable.NewMap[string, int](r.Raw),
	}
}

func copyImSidecar(s ImSidecar) ImSidecar {
	return s
}
