package main

import (
	"testing"

	"github.com/kylelemons/godebug/pretty"
)

func TestValidate(t *testing.T) {
	tests := []struct {
		name    string
		cfg     config
		wantErr bool
	}{
		{
			name: "Success: exported name with two members",
			cfg:  config{name: "Candy", members: []string{"Twix", "ThreeMuskateers"}},
		},
		{
			name: "Success: unexported name with one member",
			cfg:  config{name: "candy", members: []string{"Twix"}},
		},
		{
			name:    "Error: missing name",
			cfg:     config{members: []string{"Twix"}},
			wantErr: true,
		},
		{
			name:    "Error: name is not a valid identifier",
			cfg:     config{name: "1Candy", members: []string{"Twix"}},
			wantErr: true,
		},
		{
			name:    "Error: missing members",
			cfg:     config{name: "Candy"},
			wantErr: true,
		},
		{
			name:    "Error: member is not a valid identifier",
			cfg:     config{name: "Candy", members: []string{"Tw-ix"}},
			wantErr: true,
		},
		{
			name:    "Error: member shares the union name",
			cfg:     config{name: "Candy", members: []string{"Candy"}},
			wantErr: true,
		},
		{
			name:    "Error: duplicate member",
			cfg:     config{name: "Candy", members: []string{"Twix", "Twix"}},
			wantErr: true,
		},
	}

	for _, test := range tests {
		err := test.cfg.validate()
		switch {
		case err == nil && test.wantErr:
			t.Errorf("TestValidate(%s): got err == nil, want err != nil", test.name)
		case err != nil && !test.wantErr:
			t.Errorf("TestValidate(%s): got err == %s, want err == nil", test.name, err)
		}
	}
}

func TestGenerate(t *testing.T) {
	tests := []struct {
		name string
		cfg  config
		want string
	}{
		{
			name: "Success: exported union with two members",
			cfg: config{
				pkg:     "candy",
				name:    "Candy",
				members: []string{"Twix", "ThreeMuskateers"},
				args:    []string{"-n", "Candy", "-t", "Twix,ThreeMuskateers"},
			},
			want: candyGolden,
		},
		{
			name: "Success: unexported union has lower-cased discriminator",
			cfg: config{
				pkg:     "candy",
				name:    "candy",
				members: []string{"Twix"},
				args:    []string{"-n", "candy", "-t", "Twix"},
			},
			want: lowerGolden,
		},
		{
			name: "Success: noAny union stores members in typed fields",
			cfg: config{
				pkg:     "candy",
				name:    "Candy",
				members: []string{"Twix", "ThreeMuskateers"},
				noAny:   true,
				args:    []string{"-n", "Candy", "-t", "Twix,ThreeMuskateers", "-noAny"},
			},
			want: noAnyGolden,
		},
	}

	for _, test := range tests {
		got, err := generate(test.cfg)
		if err != nil {
			t.Errorf("TestGenerate(%s): got err == %s, want err == nil", test.name, err)
			continue
		}
		if diff := pretty.Compare(test.want, string(got)); diff != "" {
			t.Errorf("TestGenerate(%s): -want/+got:\n%s", test.name, diff)
		}
	}
}

const candyGolden = `// Code generated by "union -n Candy -t Twix,ThreeMuskateers"; DO NOT EDIT.

package candy

import "strconv"

// CandyType is the discriminator for the Candy union. It reports which
// member type a Candy currently holds.
type CandyType uint8

const (
	// CandyTypeNotSet indicates the Candy holds no member; it is the zero value.
	CandyTypeNotSet CandyType = 0
	// CandyTypeTwix indicates the Candy holds a Twix.
	CandyTypeTwix CandyType = 1
	// CandyTypeThreeMuskateers indicates the Candy holds a ThreeMuskateers.
	CandyTypeThreeMuskateers CandyType = 2
)

const _CandyType_name = "CandyTypeNotSetCandyTypeTwixCandyTypeThreeMuskateers"

var _CandyType_index = [...]uint8{0, 15, 28, 52}

// String returns the name of the CandyType constant, or, for an unknown
// value, "CandyType(N)" where N is the underlying integer.
func (t CandyType) String() string {
	if int(t) >= len(_CandyType_index)-1 {
		return "CandyType(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return _CandyType_name[_CandyType_index[t]:_CandyType_index[t+1]]
}

// Candy is a union type that holds exactly one of the following member
// types: Twix, ThreeMuskateers. The zero value holds no member; use a Set method to set one.
type Candy struct {
	t CandyType
	v any
}

// Type reports which member type c currently holds.
func (c *Candy) Type() CandyType {
	return c.t
}

// SetTwix unsets c's current member, if any, sets it to a Twix
// holding v, and returns v.
func (c *Candy) SetTwix(v Twix) Twix {
	*c = Candy{}
	c.t = CandyTypeTwix
	c.v = v
	return v
}

// Twix returns the Twix held by c. If c does not hold a
// Twix, the zero value is returned; compare c.Type() to CandyTypeTwix to
// distinguish a held zero value from an absent one.
func (c *Candy) Twix() Twix {
	if c.t != CandyTypeTwix {
		var v Twix
		return v
	}
	return c.v.(Twix)
}

// SetThreeMuskateers unsets c's current member, if any, sets it to a ThreeMuskateers
// holding v, and returns v.
func (c *Candy) SetThreeMuskateers(v ThreeMuskateers) ThreeMuskateers {
	*c = Candy{}
	c.t = CandyTypeThreeMuskateers
	c.v = v
	return v
}

// ThreeMuskateers returns the ThreeMuskateers held by c. If c does not hold a
// ThreeMuskateers, the zero value is returned; compare c.Type() to CandyTypeThreeMuskateers to
// distinguish a held zero value from an absent one.
func (c *Candy) ThreeMuskateers() ThreeMuskateers {
	if c.t != CandyTypeThreeMuskateers {
		var v ThreeMuskateers
		return v
	}
	return c.v.(ThreeMuskateers)
}
`

const lowerGolden = `// Code generated by "union -n candy -t Twix"; DO NOT EDIT.

package candy

import "strconv"

// candyType is the discriminator for the candy union. It reports which
// member type a candy currently holds.
type candyType uint8

const (
	// candyTypeNotSet indicates the candy holds no member; it is the zero value.
	candyTypeNotSet candyType = 0
	// candyTypeTwix indicates the candy holds a Twix.
	candyTypeTwix candyType = 1
)

const _candyType_name = "candyTypeNotSetcandyTypeTwix"

var _candyType_index = [...]uint8{0, 15, 28}

// String returns the name of the candyType constant, or, for an unknown
// value, "candyType(N)" where N is the underlying integer.
func (t candyType) String() string {
	if int(t) >= len(_candyType_index)-1 {
		return "candyType(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return _candyType_name[_candyType_index[t]:_candyType_index[t+1]]
}

// candy is a union type that holds exactly one of the following member
// types: Twix. The zero value holds no member; use a Set method to set one.
type candy struct {
	t candyType
	v any
}

// Type reports which member type c currently holds.
func (c *candy) Type() candyType {
	return c.t
}

// SetTwix unsets c's current member, if any, sets it to a Twix
// holding v, and returns v.
func (c *candy) SetTwix(v Twix) Twix {
	*c = candy{}
	c.t = candyTypeTwix
	c.v = v
	return v
}

// Twix returns the Twix held by c. If c does not hold a
// Twix, the zero value is returned; compare c.Type() to candyTypeTwix to
// distinguish a held zero value from an absent one.
func (c *candy) Twix() Twix {
	if c.t != candyTypeTwix {
		var v Twix
		return v
	}
	return c.v.(Twix)
}
`

const noAnyGolden = `// Code generated by "union -n Candy -t Twix,ThreeMuskateers -noAny"; DO NOT EDIT.

package candy

import "strconv"

// CandyType is the discriminator for the Candy union. It reports which
// member type a Candy currently holds.
type CandyType uint8

const (
	// CandyTypeNotSet indicates the Candy holds no member; it is the zero value.
	CandyTypeNotSet CandyType = 0
	// CandyTypeTwix indicates the Candy holds a Twix.
	CandyTypeTwix CandyType = 1
	// CandyTypeThreeMuskateers indicates the Candy holds a ThreeMuskateers.
	CandyTypeThreeMuskateers CandyType = 2
)

const _CandyType_name = "CandyTypeNotSetCandyTypeTwixCandyTypeThreeMuskateers"

var _CandyType_index = [...]uint8{0, 15, 28, 52}

// String returns the name of the CandyType constant, or, for an unknown
// value, "CandyType(N)" where N is the underlying integer.
func (t CandyType) String() string {
	if int(t) >= len(_CandyType_index)-1 {
		return "CandyType(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return _CandyType_name[_CandyType_index[t]:_CandyType_index[t+1]]
}

// Candy is a union type that holds exactly one of the following member
// types: Twix, ThreeMuskateers. The zero value holds no member; use a Set method to set one.
type Candy struct {
	t                CandyType
	vTwix            Twix
	vThreeMuskateers ThreeMuskateers
}

// Type reports which member type c currently holds.
func (c *Candy) Type() CandyType {
	return c.t
}

// SetTwix unsets c's current member, if any, sets it to a Twix
// holding v, and returns v.
func (c *Candy) SetTwix(v Twix) Twix {
	*c = Candy{}
	c.t = CandyTypeTwix
	c.vTwix = v
	return v
}

// Twix returns the Twix held by c. If c does not hold a
// Twix, the zero value is returned; compare c.Type() to CandyTypeTwix to
// distinguish a held zero value from an absent one.
func (c *Candy) Twix() Twix {
	return c.vTwix
}

// SetThreeMuskateers unsets c's current member, if any, sets it to a ThreeMuskateers
// holding v, and returns v.
func (c *Candy) SetThreeMuskateers(v ThreeMuskateers) ThreeMuskateers {
	*c = Candy{}
	c.t = CandyTypeThreeMuskateers
	c.vThreeMuskateers = v
	return v
}

// ThreeMuskateers returns the ThreeMuskateers held by c. If c does not hold a
// ThreeMuskateers, the zero value is returned; compare c.Type() to CandyTypeThreeMuskateers to
// distinguish a held zero value from an absent one.
func (c *Candy) ThreeMuskateers() ThreeMuskateers {
	return c.vThreeMuskateers
}
`
