// Code generated by immutable tool. DO NOT EDIT.

package data

import ()

// ImShadowed is an immutable version of Shadowed.
// Shadowed is the real, file-scope target.
type ImShadowed struct {
	name string // Name is a plain scalar field.
}

// GetName retrieves the content of the field Name.
// Name is a plain scalar field.
func (r *ImShadowed) GetName() string {
	return r.name
}

// SetName returns a copy of the struct with the field Name set to the new value.
// Name is a plain scalar field.
func (r *ImShadowed) SetName(value string) ImShadowed {
	n := copyImShadowed(*r)
	n.name = value
	return n
}

// Mutable converts the immutable struct back to the original mutable struct.
func (r *ImShadowed) Mutable() Shadowed {
	return Shadowed{
		Name: r.name,
	}
}

// Immutable converts the mutable struct to the generated immutable struct.
func (r *Shadowed) Immutable() ImShadowed {
	return ImShadowed{
		name: r.Name,
	}
}

func copyImShadowed(s ImShadowed) ImShadowed {
	return s
}
