// Code generated by immutable tool. DO NOT EDIT.

package data

import (
	"github.com/gostdlib/base/values/immutable"
)

// ImPreDeclared is an immutable version of PreDeclared.
//
//	pre := PreDeclared{}
//	use(pre)
//
// PreDeclared opens its doc comment with a code block, which must stay a code block, and holds a field
// the author already wrote as an immutable type. That field is passed through rather than wrapped again,
// and the immutable import must not be emitted twice.
type ImPreDeclared struct {
	mapping immutable.Map[string, int] // Mapping is already immutable, so the conversions leave it alone.
	raw     immutable.Map[string, int] // Raw is a plain map, so the generator wraps it and the conversions copy.
}

// GetMapping retrieves the content of the field Mapping.
// Mapping is already immutable, so the conversions leave it alone.
func (r *ImPreDeclared) GetMapping() immutable.Map[string, int] {
	return r.mapping
}

// SetMapping returns a copy of the struct with the field Mapping set to the new value.
// Mapping is already immutable, so the conversions leave it alone.
func (r *ImPreDeclared) SetMapping(value immutable.Map[string, int]) ImPreDeclared {
	n := copyImPreDeclared(*r)
	n.mapping = value
	return n
}

// GetRaw retrieves the content of the field Raw.
// Raw is a plain map, so the generator wraps it and the conversions copy.
func (r *ImPreDeclared) GetRaw() immutable.Map[string, int] {
	return r.raw
}

// SetRaw returns a copy of the struct with the field Raw set to the new value.
// Raw is a plain map, so the generator wraps it and the conversions copy.
func (r *ImPreDeclared) SetRaw(value immutable.Map[string, int]) ImPreDeclared {
	n := copyImPreDeclared(*r)
	n.raw = value
	return n
}

// Mutable converts the immutable struct back to the original mutable struct.
// The maps and slices this type wrapped are copied one level deep, so the returned value can be modified without
// changing the immutable one. A field declared immutable in PreDeclared is returned as it is.
func (r *ImPreDeclared) Mutable() PreDeclared {
	return PreDeclared{
		Mapping: r.mapping,
		Raw:     r.raw.Copy(),
	}
}

// Immutable converts the mutable struct to the generated immutable struct.
// Every map and slice is shared with the returned value rather than copied, so PreDeclared must not be used
// again after this call: writing to it would change the value returned here. Generate with -copy if both need to
// stay usable.
func (r *PreDeclared) Immutable() ImPreDeclared {
	return ImPreDeclared{
		mapping: r.Mapping,
		raw:     immutable.NewMap[string, int](r.Raw),
	}
}

func copyImPreDeclared(s ImPreDeclared) ImPreDeclared {
	return s
}
