// Code generated by "stringer -type=Category -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CatUnknown-0]
	_ = x[CatRequest-1]
	_ = x[CatSafety-2]
	_ = x[CatPermission-3]
	_ = x[CatResourceExhausted-4]
	_ = x[CatInternal-5]
}

const _Category_name = "UnknownRequestSafetyPermissionResourceExhaustedInternal"

var _Category_index = [...]uint8{0, 7, 14, 20, 30, 47, 55}

func (i Category) String() string {
	if i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
