// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeBadRequest-1]
	_ = x[TypeDeadTimer-101]
	_ = x[TypeClusterHealth-102]
	_ = x[TypePermissionDenied-201]
}

const (
	_Type_name_0 = "UnknownBadRequest"
	_Type_name_1 = "DeadTimerClusterHealth"
	_Type_name_2 = "PermissionDenied"
)

var (
	_Type_index_0 = [...]uint8{0, 7, 17}
	_Type_index_1 = [...]uint8{0, 9, 22}
)

func (i Type) String() string {
	switch {
	case i <= 1:
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case 101 <= i && i <= 102:
		i -= 101
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	case i == 201:
		return _Type_name_2
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
