// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: errors/example/proto/example.proto

package example

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCategory defines the category of an error.
type ErrorCategory int32

const (
	// The error is unknown. This is always a bug from the service.
	ErrorCategory_EC_UNKNOWN ErrorCategory = 0
	// The error is caused by the request being incorrect.
	ErrorCategory_EC_REQUEST ErrorCategory = 1
	// The error is caused by a safety issue.
	ErrorCategory_EC_SAFETY ErrorCategory = 2
	// The error is caused by a permission issue.
	ErrorCategory_EC_PERMISSION ErrorCategory = 3
	// The error is caused by a resource being exhausted.
	ErrorCategory_EC_RESOURCE_EXHAUSTED ErrorCategory = 4
	// The error is caused by an internal issue.
	ErrorCategory_EC_INTERNAL ErrorCategory = 5
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "EC_UNKNOWN",
		1: "EC_REQUEST",
		2: "EC_SAFETY",
		3: "EC_PERMISSION",
		4: "EC_RESOURCE_EXHAUSTED",
		5: "EC_INTERNAL",
	}
	ErrorCategory_value = map[string]int32{
		"EC_UNKNOWN":            0,
		"EC_REQUEST":            1,
		"EC_SAFETY":             2,
		"EC_PERMISSION":         3,
		"EC_RESOURCE_EXHAUSTED": 4,
		"EC_INTERNAL":           5,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_example_proto_example_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_errors_example_proto_example_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_errors_example_proto_example_proto_rawDescGZIP(), []int{0}
}

// ErrorType represents the type of the error.
type ErrorType int32

const (
	// The error type is unknown. This is always a bug from the service.
	ErrorType_ET_UNKNOWN ErrorType = 0
	// 1-100 are RPC errors.
	//
	// The error is caused by a bad request.
	ErrorType_ET_BAD_REQUEST ErrorType = 1
	// 101-200 are safety errors.
	//
	// The error is caused by a dead timer.
	ErrorType_ET_DEAD_TIMER ErrorType = 101
	// The error is caused by the cluster being unhealthy.
	ErrorType_ET_CLUSTER_HEALTH ErrorType = 102
	// 201-300 are permission errors.
	//
	// The error is caused by permission being denied.
	ErrorType_ET_PERMISSION_DENIED ErrorType = 201
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0:   "ET_UNKNOWN",
		1:   "ET_BAD_REQUEST",
		101: "ET_DEAD_TIMER",
		102: "ET_CLUSTER_HEALTH",
		201: "ET_PERMISSION_DENIED",
	}
	ErrorType_value = map[string]int32{
		"ET_UNKNOWN":           0,
		"ET_BAD_REQUEST":       1,
		"ET_DEAD_TIMER":        101,
		"ET_CLUSTER_HEALTH":    102,
		"ET_PERMISSION_DENIED": 201,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_example_proto_example_proto_enumTypes[1].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_errors_example_proto_example_proto_enumTypes[1]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_errors_example_proto_example_proto_rawDescGZIP(), []int{1}
}

// Error provides details on an error. When a request fails, this will be JSON encoded with jsonpb
// in the status message that is returned.
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the request. This is the UUIDv7 identity of the request.
	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// The category of the error.
	Category ErrorCategory `protobuf:"varint,2,opt,name=Category,proto3,enum=github.com.gostdlib.base.proto.example.ErrorCategory" json:"Category,omitempty"`
	// The type of the error.
	Type ErrorType `protobuf:"varint,3,opt,name=Type,proto3,enum=github.com.gostdlib.base.proto.example.ErrorType" json:"Type,omitempty"`
	// The error message. This may be an error string, JSON encoded, or both.
	Msg string `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	// The original request.
	Request *anypb.Any `protobuf:"bytes,5,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_example_proto_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_errors_example_proto_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_errors_example_proto_example_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Error) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_EC_UNKNOWN
}

func (x *Error) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_ET_UNKNOWN
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Error) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_example_proto_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_errors_example_proto_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_errors_example_proto_example_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_example_proto_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_errors_example_proto_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_errors_example_proto_example_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_errors_example_proto_example_proto protoreflect.FileDescriptor

var file_errors_example_proto_example_proto_rawDesc = []byte{
	0x0a, 0x22, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x6f, 0x73, 0x74, 0x64, 0x6c, 0x69, 0x62, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x51, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x35, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x6f, 0x73, 0x74, 0x64, 0x6c, 0x69, 0x62, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x45, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x31, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f,
	0x73, 0x74, 0x64, 0x6c, 0x69, 0x62, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x08, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x09, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x2a, 0x7d, 0x0a, 0x0d, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x0a, 0x45,
	0x43, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45,
	0x43, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x45,
	0x43, 0x5f, 0x53, 0x41, 0x46, 0x45, 0x54, 0x59, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x43,
	0x5f, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x19, 0x0a,
	0x15, 0x45, 0x43, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x45, 0x58, 0x48,
	0x41, 0x55, 0x53, 0x54, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x43, 0x5f, 0x49,
	0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x05, 0x2a, 0x74, 0x0a, 0x09, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x54, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x54, 0x5f, 0x42, 0x41, 0x44,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x54,
	0x5f, 0x44, 0x45, 0x41, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x52, 0x10, 0x65, 0x12, 0x15, 0x0a,
	0x11, 0x45, 0x54, 0x5f, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41, 0x4c,
	0x54, 0x48, 0x10, 0x66, 0x12, 0x19, 0x0a, 0x14, 0x45, 0x54, 0x5f, 0x50, 0x45, 0x52, 0x4d, 0x49,
	0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0xc9, 0x01, 0x32,
	0x90, 0x01, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x86, 0x01, 0x0a, 0x05, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x30, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x6f, 0x73, 0x74, 0x64, 0x6c, 0x69, 0x62, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x31, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x73, 0x74, 0x64, 0x6c, 0x69, 0x62, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12,
	0x3a, 0x01, 0x2a, 0x22, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x6f, 0x73, 0x74, 0x64, 0x6c, 0x69, 0x62, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_errors_example_proto_example_proto_rawDescOnce sync.Once
	file_errors_example_proto_example_proto_rawDescData = file_errors_example_proto_example_proto_rawDesc
)

func file_errors_example_proto_example_proto_rawDescGZIP() []byte {
	file_errors_example_proto_example_proto_rawDescOnce.Do(func() {
		file_errors_example_proto_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_errors_example_proto_example_proto_rawDescData)
	})
	return file_errors_example_proto_example_proto_rawDescData
}

var file_errors_example_proto_example_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_errors_example_proto_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_errors_example_proto_example_proto_goTypes = []interface{}{
	(ErrorCategory)(0), // 0: github.com.gostdlib.base.proto.example.ErrorCategory
	(ErrorType)(0),     // 1: github.com.gostdlib.base.proto.example.ErrorType
	(*Error)(nil),      // 2: github.com.gostdlib.base.proto.example.Error
	(*HelloReq)(nil),   // 3: github.com.gostdlib.base.proto.example.HelloReq
	(*HelloResp)(nil),  // 4: github.com.gostdlib.base.proto.example.HelloResp
	(*anypb.Any)(nil),  // 5: google.protobuf.Any
}
var file_errors_example_proto_example_proto_depIdxs = []int32{
	0, // 0: github.com.gostdlib.base.proto.example.Error.Category:type_name -> github.com.gostdlib.base.proto.example.ErrorCategory
	1, // 1: github.com.gostdlib.base.proto.example.Error.Type:type_name -> github.com.gostdlib.base.proto.example.ErrorType
	5, // 2: github.com.gostdlib.base.proto.example.Error.Request:type_name -> google.protobuf.Any
	3, // 3: github.com.gostdlib.base.proto.example.Hello.Hello:input_type -> github.com.gostdlib.base.proto.example.HelloReq
	4, // 4: github.com.gostdlib.base.proto.example.Hello.Hello:output_type -> github.com.gostdlib.base.proto.example.HelloResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_errors_example_proto_example_proto_init() }
func file_errors_example_proto_example_proto_init() {
	if File_errors_example_proto_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_errors_example_proto_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_example_proto_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_example_proto_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errors_example_proto_example_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_errors_example_proto_example_proto_goTypes,
		DependencyIndexes: file_errors_example_proto_example_proto_depIdxs,
		EnumInfos:         file_errors_example_proto_example_proto_enumTypes,
		MessageInfos:      file_errors_example_proto_example_proto_msgTypes,
	}.Build()
	File_errors_example_proto_example_proto = out.File
	file_errors_example_proto_example_proto_rawDesc = nil
	file_errors_example_proto_example_proto_goTypes = nil
	file_errors_example_proto_example_proto_depIdxs = nil
}
