// Code generated by "stringer -type=ResultKind -linecomment"; DO NOT EDIT.

package dynamic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RKUnknown-0]
	_ = x[Received-1]
	_ = x[Closed-2]
	_ = x[Sent-3]
	_ = x[CtxDone-4]
	_ = x[Defaulted-5]
}

const _ResultKind_name = "UnknownReceivedClosedSentCtxDoneDefaulted"

var _ResultKind_index = [...]uint8{0, 7, 15, 21, 25, 32, 41}

func (i ResultKind) String() string {
	idx := int(i) - 0
	if idx >= len(_ResultKind_index)-1 {
		return "ResultKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResultKind_name[_ResultKind_index[idx]:_ResultKind_index[idx+1]]
}
