// Code generated by immutable tool. DO NOT EDIT.

package data

import (
	"github.com/gostdlib/base/values/immutable"
)

// ImMultiLine is an immutable version of MultiLine.
// MultiLine exercises doc comments that span more than one line. ast.CommentGroup.Text() strips the "//" markers
// but keeps the line breaks, so every line after the first needs its own marker in the generated file.
type ImMultiLine struct {
	// ID has a comment that also spans two lines, so it must be lifted to a doc comment above the field
	// rather than collapsed into one very long trailing comment, and repeated on the getter and setter.
	id   uint64
	name string // Name has a single line comment, which must keep working.
	tags immutable.Map[string, struct{}]
}

// GetID retrieves the content of the field ID.
// ID has a comment that also spans two lines, so it must be lifted to a doc comment above the field
// rather than collapsed into one very long trailing comment, and repeated on the getter and setter.
func (r *ImMultiLine) GetID() uint64 {
	return r.id
}

// SetID returns a copy of the struct with the field ID set to the new value.
// ID has a comment that also spans two lines, so it must be lifted to a doc comment above the field
// rather than collapsed into one very long trailing comment, and repeated on the getter and setter.
func (r *ImMultiLine) SetID(value uint64) ImMultiLine {
	n := copyImMultiLine(*r)
	n.id = value
	return n
}

// GetName retrieves the content of the field Name.
// Name has a single line comment, which must keep working.
func (r *ImMultiLine) GetName() string {
	return r.name
}

// SetName returns a copy of the struct with the field Name set to the new value.
// Name has a single line comment, which must keep working.
func (r *ImMultiLine) SetName(value string) ImMultiLine {
	n := copyImMultiLine(*r)
	n.name = value
	return n
}

// GetTags retrieves the content of the field Tags.
func (r *ImMultiLine) GetTags() immutable.Map[string, struct{}] {
	return r.tags
}

// SetTags returns a copy of the struct with the field Tags set to the new value.
func (r *ImMultiLine) SetTags(value immutable.Map[string, struct{}]) ImMultiLine {
	n := copyImMultiLine(*r)
	n.tags = value
	return n
}

// Mutable converts the immutable struct back to the original mutable struct.
func (r *ImMultiLine) Mutable() MultiLine {
	return MultiLine{
		ID:   r.id,
		Name: r.name,
		Tags: r.tags.Copy(),
	}
}

// Immutable converts the mutable struct to the generated immutable struct.
func (r *MultiLine) Immutable() ImMultiLine {
	return ImMultiLine{
		id:   (r.ID),
		name: (r.Name),
		tags: immutable.NewMap[string, struct{}](r.Tags),
	}
}

func copyImMultiLine(s ImMultiLine) ImMultiLine {
	return s
}
